export const Marital_Status = [
    { value: 'never_married', label: 'Never Married' },
    { value: 'divorced', label: 'Divorced' },
    { value: 'widowed', label: 'Widowed' },
];

export const Gender = [
    { value: 'male', label: 'Male' },
    { value: 'female', label: 'Female' },
];

export const Height = [
    { value: 'fourzero', label: `4' 0" (121 cm)` },
    { value: 'fourone', label: `4' 1" (124 cm)` },
    { value: 'fourtwo', label: `4' 2" (127 cm)` },
    { value: 'fourthree', label: `4' 3" (129 cm)` },
    { value: 'fourfour', label: `4' 4" (132 cm)` },
    { value: 'fourfive', label: `4' 5" (134 cm)` },
    { value: 'foursix', label: `4' 6" (137 cm)` },
    { value: 'fourseven', label: `4' 7" (139 cm)` },
    { value: 'foureight', label: `4' 8" (142 cm)` },
    { value: 'fournine', label: `4' 9" (144 cm)` },
    { value: 'fourten', label: `4' 10" (147 cm)` },
    { value: 'foureleven', label: `4' 11" (149 cm)` },
    { value: 'fivezero', label: `5' 0" (152 cm)` },
    { value: 'fiveone', label: `5' 1" (154 cm)` },
    { value: 'fivetwo', label: `5' 2" (157 cm)` },
    { value: 'fivethree', label: `5' 3" (160 cm)` },
    { value: 'fivefour', label: `5' 4" (162 cm)` },
    { value: 'fivefive', label: `5' 5" (165 cm)` },
    { value: 'fivesix', label: `5' 6" (167 cm)` },
    { value: 'fiveseven', label: `5' 7" (170 cm)` },
    { value: 'fiveeight', label: `5' 8" (172 cm)` },
    { value: 'fivenine', label: `5' 9" (175 cm)` },
    { value: 'fiveten', label: `5' 10" (177 cm)` },
    { value: 'fiveeleven', label: `5' 11" (180 cm)` },
    { value: 'sixzero', label: `6' 0" (182 cm)` },
    { value: 'sixone', label: `6' 1" (185 cm)` },
    { value: 'sixtwo', label: `6' 2" (187 cm)` },
    { value: 'sixthree', label: `6' 3" (190 cm)` },
    { value: 'sixfour', label: `6' 4" (193 cm)` },
    { value: 'sixfive', label: `6' 5" (195 cm)` },
    { value: 'sixsix', label: `6' 6" (198 cm)` },
    { value: 'sixseven', label: `6' 7" (200 cm)` },
    { value: 'sixeight', label: `6' 8" (203 cm)` },
    { value: 'sixnine', label: `6' 9" (205 cm)` },
    { value: 'sixten', label: `6' 10" (208 cm)` },
    { value: 'sixeleven', label: `6' 11" (210 cm)` },
];

export const IndianState = [
    { value: 'AN', label: 'Andaman and Nicobar Islands' },
    { value: 'AP', label: 'Andhra Pradesh' },
    { value: 'AR', label: 'Arunachal Pradesh' },
    { value: 'AS', label: 'Assam' },
    { value: 'BR', label: 'Bihar' },
    { value: 'CG', label: 'Chandigarh' },
    { value: 'CH', label: 'Chhattisgarh' },
    { value: 'DH', label: 'Dadra and Nagar Haveli' },
    { value: 'DD', label: 'Daman and Diu' },
    { value: 'DL', label: 'Delhi' },
    { value: 'GA', label: 'Goa' },
    { value: 'GJ', label: 'Gujarat' },
    { value: 'HR', label: 'Haryana' },
    { value: 'HP', label: 'Himachal Pradesh' },
    { value: 'JK', label: 'Jammu and Kashmir' },
    { value: 'JH', label: 'Jharkhand' },
    { value: 'KA', label: 'Karnataka' },
    { value: 'KL', label: 'Kerala' },
    { value: 'LD', label: 'Lakshadweep' },
    { value: 'MP', label: 'Madhya Pradesh' },
    { value: 'MH', label: 'Maharashtra' },
    { value: 'MN', label: 'Manipur' },
    { value: 'ML', label: 'Meghalaya' },
    { value: 'MZ', label: 'Mizoram' },
    { value: 'NL', label: 'Nagaland' },
    { value: 'OR', label: 'Odisha' },
    { value: 'PY', label: 'Puducherry' },
    { value: 'PB', label: 'Punjab' },
    { value: 'RJ', label: 'Rajasthan' },
    { value: 'SK', label: 'Sikkim' },
    { value: 'TN', label: 'Tamil Nadu' },
    { value: 'TS', label: 'Telangana' },
    { value: 'TR', label: 'Tripura' },
    { value: 'UK', label: 'Uttarakhand' },
    { value: 'UP', label: 'Uttar Pradesh' },
    { value: 'WB', label: 'West Bengal' },
];

export const EmployedSectors = [
    { value: 'private_sector', label: 'Private Sector' },
    { value: 'government', label: 'Government/Public Sector' },
    { value: 'civil_services', label: 'Civil Services' },
    { value: 'defense', label: 'Defense' },
    { value: 'business', label: 'Business/Self-Employed' },
    { value: 'not_working', label: 'Not Working' },
];

export const AnnualIncome = [
    { value: 'no_income', label: 'No income' },
    { value: '0-3', label: 'Rs. 0 - 3 lacs' },
    { value: '3-6', label: 'Rs. 3 - 6 lacs' },
    { value: '6-9', label: 'Rs. 6 - 9 lacs' },
    { value: '9-12', label: 'Rs. 9 - 12 lacs' },
    { value: '12-15', label: 'Rs. 12 - 15 lacs' },
    { value: '15-18', label: 'Rs. 15 - 18 lacs' },
    { value: '18-21', label: 'Rs. 18 - 21 lacs' },
    { value: '21-24', label: 'Rs. 21 - 24 lacs' },
    { value: 'above_24', label: 'Above Rs. 24 lacs' },
];

export const Gotra = [
    { value: 'aast', label: 'Aast' },
    { value: 'aagechal', label: 'Aagechal' },
    { value: 'aahoriya ', label: 'Aahoriya ' },
    { value: 'aal', label: 'Aal' },
    { value: 'aars', label: 'Aars' },
    { value: 'aasat', label: 'Aasat' },
    { value: 'aasth', label: 'Aasth' },
    { value: 'achala', label: 'achala' },
    { value: 'achil', label: 'Achil' },
    { value: 'adahake', label: 'Adahake' },
    { value: 'adaniya', label: 'Adaniya' },
    { value: 'adapiya', label: 'Adapiya' },
    { value: 'adhera', label: 'Adhera' },
    { value: 'adhupiya', label: 'Adhupiya' },
    { value: 'adok', label: 'Adok' },
    { value: 'adwal', label: 'Adwal' },
    { value: 'agroya', label: 'Agroya' },
    { value: 'ahibhe', label: 'Ahibhe' },
    { value: 'ahike', label: 'Ahike' },
    { value: 'ajora', label: 'Ajora' },
    { value: 'ajwal', label: 'Ajwal' },
    { value: 'aldayan', label: 'Aldayan' },
    { value: 'alvan', label: 'Alvan' },
    { value: 'amarval', label: 'Amarval' },
    { value: 'amora', label: 'Amora' },
    { value: 'anchal', label: 'Anchal' },
    { value: 'andhra', label: 'Andhra' },
    { value: 'anth', label: 'Anth' },
    { value: 'asveriya', label: 'Asveriya' },
    { value: 'atrapura', label: 'Atrapura' },
    { value: 'babeliya', label: 'Babeliya' },
    { value: 'babera', label: 'Babera' },
    { value: 'baberwal', label: 'Baberwal' },
    { value: 'bachan', label: 'Bachan' },
    { value: 'bachhas', label: 'Bachhas' },
    { value: 'badbalas', label: 'Badbalas' },
    { value: 'badbecha', label: 'Badbecha' },
    { value: 'badgota', label: 'Badgota' },
    { value: 'badhoriya', label: 'Badhoriya' },
    { value: 'badliya', label: 'Badliya' },
    { value: 'badsola', label: 'Badsola' },
    { value: 'badwal', label: 'Badwal' },
    { value: 'baga', label: 'Baga' },
    { value: 'bage', label: 'Bage' },
    { value: 'bahamwal', label: 'Bahamwal' },
    { value: 'baharan', label: 'Baharan' },
    { value: 'bahubala', label: 'Bahubala' },
    { value: 'baida', label: 'Baida' },
    { value: 'bajarjuda', label: 'Bajarjuda' },
    { value: 'bakan', label: 'Bakan' },
    { value: 'bakaniya', label: 'Bakaniya' },
    { value: 'bamala', label: 'Bamala' },
    { value: 'bamalwa', label: 'Bamalwa' },
    { value: 'banafara', label: 'Banafara' },
    { value: 'banara', label: 'Banara' },
    { value: 'banava', label: 'Banava' },
    { value: 'banerwal', label: 'Banerwal' },
    { value: 'bans', label: 'Bans' },
    { value: 'banthiya', label: 'Banthiya' },
    { value: 'baradiya', label: 'Baradiya' },
    { value: 'barana', label: 'Barana' },
    { value: 'basiwal', label: 'Basiwal' },
    { value: 'bamala', label: 'Bamala' },
    { value: 'bathara', label: 'Bathara' },
    { value: 'bathotha', label: 'Bathotha' },
    { value: 'bechas', label: 'Bechas' },
    { value: 'bhadaliya', label: 'Bhadaliya' },
    { value: 'bhajawal', label: 'Bhajawal' },
    { value: 'bhajiwal', label: 'Bhajiwal' },
    { value: 'bhalas', label: 'Bhalas' },
    { value: 'bhama', label: 'Bhama' },
    { value: 'bhamesa', label: 'Bhamesa' },
    { value: 'bhamuriya', label: 'Bhamuriya' },
    { value: 'bhanu', label: 'Bhanu' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },

    { value: 'bhanwar', label: 'Bhanwar' },

    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },

    { value: 'bhanwar', label: 'Bhanwar' },

    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },

    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },

    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
    { value: 'bhanwar', label: 'Bhanwar' },
];
